import { Averia_Serif_Libre, Lilita_One } from "next/font/google";
import 'bulma/css/bulma.css';
import "./globals.css";

const lilita = Lilita_One({ subsets: ["latin"], weight: ['400'] });
const averia = Averia_Serif_Libre({ subsets: ["latin"], weight: ['300', '400', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={averia.className}>{children}</body>
    </html>
  );
}
